/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubRouteImport } from './routes/club'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as PracticesRouteImport } from './routes/practices'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as PlaybookIndexRouteImport } from './routes/playbook.index'
import { Route as PlaybookPlayIdRouteImport } from './routes/playbook.$playId'
import { Route as PracticesIndexRouteImport } from './routes/practices.index'
import { Route as PracticesPlanIdRouteImport } from './routes/practices.$planId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PracticesPlanIdIndexRouteImport } from './routes/practices.$planId.index'
import { Route as PracticesPlanIdRunRouteImport } from './routes/practices.$planId.run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesRoute = PracticesRouteImport.update({
  id: '/practices',
  path: '/practices',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookIndexRoute = PlaybookIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaybookRoute,
} as any)
const PlaybookPlayIdRoute = PlaybookPlayIdRouteImport.update({
  id: '/$playId',
  path: '/$playId',
  getParentRoute: () => PlaybookRoute,
} as any)
const PracticesIndexRoute = PracticesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticesRoute,
} as any)
const PracticesPlanIdRoute = PracticesPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => PracticesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticesPlanIdIndexRoute = PracticesPlanIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticesPlanIdRoute,
} as any)
const PracticesPlanIdRunRoute = PracticesPlanIdRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => PracticesPlanIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/practices': typeof PracticesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/subscribe': typeof SubscribeRoute
  '/playbook/$playId': typeof PlaybookPlayIdRoute
  '/practices/$planId': typeof PracticesPlanIdRouteWithChildren
  '/playbook/': typeof PlaybookIndexRoute
  '/practices/': typeof PracticesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/practices/$planId/run': typeof PracticesPlanIdRunRoute
  '/practices/$planId/': typeof PracticesPlanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/subscribe': typeof SubscribeRoute
  '/playbook/$playId': typeof PlaybookPlayIdRoute
  '/playbook': typeof PlaybookIndexRoute
  '/practices': typeof PracticesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/practices/$planId/run': typeof PracticesPlanIdRunRoute
  '/practices/$planId': typeof PracticesPlanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/login': typeof LoginRoute
  '/playbook': typeof PlaybookRouteWithChildren
  '/practices': typeof PracticesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/subscribe': typeof SubscribeRoute
  '/playbook/$playId': typeof PlaybookPlayIdRoute
  '/practices/$planId': typeof PracticesPlanIdRouteWithChildren
  '/playbook/': typeof PlaybookIndexRoute
  '/practices/': typeof PracticesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/practices/$planId/run': typeof PracticesPlanIdRunRoute
  '/practices/$planId/': typeof PracticesPlanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/club'
    | '/login'
    | '/playbook'
    | '/practices'
    | '/settings'
    | '/subscribe'
    | '/playbook/$playId'
    | '/practices/$planId'
    | '/playbook/'
    | '/practices/'
    | '/api/auth/$'
    | '/practices/$planId/run'
    | '/practices/$planId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/club'
    | '/login'
    | '/settings'
    | '/subscribe'
    | '/playbook/$playId'
    | '/playbook'
    | '/practices'
    | '/api/auth/$'
    | '/practices/$planId/run'
    | '/practices/$planId'
  id:
    | '__root__'
    | '/'
    | '/club'
    | '/login'
    | '/playbook'
    | '/practices'
    | '/settings'
    | '/subscribe'
    | '/playbook/$playId'
    | '/practices/$planId'
    | '/playbook/'
    | '/practices/'
    | '/api/auth/$'
    | '/practices/$planId/run'
    | '/practices/$planId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubRoute: typeof ClubRoute
  LoginRoute: typeof LoginRoute
  PlaybookRoute: typeof PlaybookRouteWithChildren
  PracticesRoute: typeof PracticesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SubscribeRoute: typeof SubscribeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices': {
      id: '/practices'
      path: '/practices'
      fullPath: '/practices'
      preLoaderRoute: typeof PracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook/': {
      id: '/playbook/'
      path: '/'
      fullPath: '/playbook/'
      preLoaderRoute: typeof PlaybookIndexRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/playbook/$playId': {
      id: '/playbook/$playId'
      path: '/$playId'
      fullPath: '/playbook/$playId'
      preLoaderRoute: typeof PlaybookPlayIdRouteImport
      parentRoute: typeof PlaybookRoute
    }
    '/practices/': {
      id: '/practices/'
      path: '/'
      fullPath: '/practices/'
      preLoaderRoute: typeof PracticesIndexRouteImport
      parentRoute: typeof PracticesRoute
    }
    '/practices/$planId': {
      id: '/practices/$planId'
      path: '/$planId'
      fullPath: '/practices/$planId'
      preLoaderRoute: typeof PracticesPlanIdRouteImport
      parentRoute: typeof PracticesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practices/$planId/': {
      id: '/practices/$planId/'
      path: '/'
      fullPath: '/practices/$planId/'
      preLoaderRoute: typeof PracticesPlanIdIndexRouteImport
      parentRoute: typeof PracticesPlanIdRoute
    }
    '/practices/$planId/run': {
      id: '/practices/$planId/run'
      path: '/run'
      fullPath: '/practices/$planId/run'
      preLoaderRoute: typeof PracticesPlanIdRunRouteImport
      parentRoute: typeof PracticesPlanIdRoute
    }
  }
}

interface PlaybookRouteChildren {
  PlaybookPlayIdRoute: typeof PlaybookPlayIdRoute
  PlaybookIndexRoute: typeof PlaybookIndexRoute
}

const PlaybookRouteChildren: PlaybookRouteChildren = {
  PlaybookPlayIdRoute: PlaybookPlayIdRoute,
  PlaybookIndexRoute: PlaybookIndexRoute,
}

const PlaybookRouteWithChildren = PlaybookRoute._addFileChildren(
  PlaybookRouteChildren,
)

interface PracticesPlanIdRouteChildren {
  PracticesPlanIdRunRoute: typeof PracticesPlanIdRunRoute
  PracticesPlanIdIndexRoute: typeof PracticesPlanIdIndexRoute
}

const PracticesPlanIdRouteChildren: PracticesPlanIdRouteChildren = {
  PracticesPlanIdRunRoute: PracticesPlanIdRunRoute,
  PracticesPlanIdIndexRoute: PracticesPlanIdIndexRoute,
}

const PracticesPlanIdRouteWithChildren = PracticesPlanIdRoute._addFileChildren(
  PracticesPlanIdRouteChildren,
)

interface PracticesRouteChildren {
  PracticesPlanIdRoute: typeof PracticesPlanIdRouteWithChildren
  PracticesIndexRoute: typeof PracticesIndexRoute
}

const PracticesRouteChildren: PracticesRouteChildren = {
  PracticesPlanIdRoute: PracticesPlanIdRouteWithChildren,
  PracticesIndexRoute: PracticesIndexRoute,
}

const PracticesRouteWithChildren = PracticesRoute._addFileChildren(
  PracticesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubRoute: ClubRoute,
  LoginRoute: LoginRoute,
  PlaybookRoute: PlaybookRouteWithChildren,
  PracticesRoute: PracticesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SubscribeRoute: SubscribeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
